name:                tapl
version:             0.1.0.0
github:              "logicoffee/tapl"
license:             BSD3
author:              "Logicoffee"
maintainer:          "example@example.com"
copyright:           "2021 Logicoffee"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/logicoffee/tapl#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tapl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tapl

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tapl
    - tasty
    - tasty-hunit
    - tasty-discover
